#include "block.h"
#include "diagnostic.h"
#include "span.h"
#include "text.h"

#ifdef _HAS_SIGTRACE
#include <sigtrace.h>
#endif

#include <md4c.h>

#include <assert.h>
#include <ctype.h>
#include <errno.h>
#include <getopt.h>
#include <libgen.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>

//==============//
// Command line //
//==============//

// *INDENT-OFF*
static const char *const usage =
    "Usage: %s [OPTION...] [FILE]\n"
    "Options:\n"
    "  -h, --help    print this text\n"
    "  --version     print program version\n"
    "\n"
    "  -t TITLE      set man page title\n"
    "  -s SECTION    set man page section number\n"
    "  -d DATE       set man page center footer (last change date)\n"
    "  -S SOURCE     set man page left footer (project name and version)\n"
    "  -V VOLUME     set man page center header (section name)\n"
    "\n"
    "  --no-comment  do not output 'generated by' roff comment\n"
    "\n"
    "If FILE is '-' or omitted, reads from standard input\n"
    "\n"
    "If FILE is a filename, TITLE and SECTION can be inferred from it\n"
    "\n"
    "See md2manc(1) for details\n";
// *INDENT-ON*

static const char *const version = "md2manc version %s\n";

static void print_usage_and_exit(char *argv0)
{
    printf(usage, argv0);
    exit(0);
}

static void print_version_and_exit(void)
{
    printf(version, _PROGRAM_VERSION);
    exit(0);
}

static const char *title = NULL;
static const char *section = NULL;
static const char *date = "";
static const char *source = "";
static const char *volume = NULL;

static bool print_generated_by_comment = true;

static int parse_options(int argc, char **argv)
{
    for (;;) {
        switch (getopt(argc, argv, ":-:ht:s:d:S:V:")) {
        case '-':
            if (strcmp(optarg, "help") == 0)
                print_usage_and_exit(argv[0]);

            if (strcmp(optarg, "version") == 0)
                print_version_and_exit();

            if (strcmp(optarg, "no-comment") == 0) {
                print_generated_by_comment = false;
                continue;
            }

            error("unknown option '--%s'", optarg);
            exit(2);
        case 'h':
            print_usage_and_exit(argv[0]);
            continue;
        case 't':
            title = optarg;
            continue;
        case 's':
            section = optarg;
            continue;
        case 'd':
            date = optarg;
            continue;
        case 'S':
            source = optarg;
            continue;
        case 'V':
            volume = optarg;
            continue;
        case ':':
            error("missing argument for option '-%c'", optopt);
            exit(2);
        case '?':
            error("unknown option '-%c'", optopt);
            exit(2);
        default:
            return optind;
        }
    }
}

//============//
// Conversion //
//============//

static int print_document_header(void)
{
    if (!title)
        title = "UNTITLED";
    if (!section)
        section = "1";

    char *uptitle = strdup(title);

    if (!uptitle)
        error("out of memory");

    for (char *cur = uptitle; *cur; cur++)
        *cur = toupper(*cur);

    if (print_generated_by_comment)
        printf(".\\\" automatically generated by md2manc %s\n",
               _PROGRAM_VERSION);

    printf(".TH \"%s\" %s \"%s\" \"%s\"", uptitle, section, date, source);

    if (volume)
        printf(" \"%s\"", volume);

    printf("\n.nh\n");
    printf(".ad l\n");

    free(uptitle);
    return 0;
}

static int enter_block(MD_BLOCKTYPE type, void *detail, void *userdata)
{
    (void)userdata;

    switch (type) {
    case MD_BLOCK_DOC:
        return 0;
    case MD_BLOCK_QUOTE:
        return enter_block_quote();
    case MD_BLOCK_UL:
        return enter_unordered_list(detail);
    case MD_BLOCK_OL:
        return enter_ordered_list(detail);
    case MD_BLOCK_LI:
        return enter_list_item();
    case MD_BLOCK_HR:
        return warning("ignoring thematic break (---, ***, ___)");
    case MD_BLOCK_H:
        return enter_heading(detail);
    case MD_BLOCK_CODE:
        return enter_code_block(detail);
    case MD_BLOCK_P:
        return enter_paragraph();
    default:
        assert(!"unhandled block type");
    }
}

static int leave_block(MD_BLOCKTYPE type, void *detail, void *userdata)
{
    (void)detail;
    (void)userdata;

    switch (type) {
    case MD_BLOCK_DOC:
        return 0;
    case MD_BLOCK_QUOTE:
        return leave_block_quote();
    case MD_BLOCK_UL:
        return leave_unordered_list();
    case MD_BLOCK_OL:
        return leave_ordered_list();
    case MD_BLOCK_LI:
        return leave_list_item();
    case MD_BLOCK_HR:
        return 0;
    case MD_BLOCK_H:
        return leave_heading();
    case MD_BLOCK_CODE:
        return leave_code_block();
    case MD_BLOCK_P:
        return leave_paragraph();
    default:
        assert(!"unhandled block type");
    }
}

static int enter_span(MD_SPANTYPE type, void *detail, void *userdata)
{
    (void)userdata;

    switch (type) {
    case MD_SPAN_EM:
        return enter_emphasis();
    case MD_SPAN_STRONG:
        return enter_strong();
    case MD_SPAN_A:
        return enter_link(detail);
    case MD_SPAN_IMG:
        return enter_image();
    case MD_SPAN_CODE:
        return 0;
    default:
        assert(!"unhandled span type");
    }
}

static int leave_span(MD_SPANTYPE type, void *detail, void *userdata)
{
    (void)detail;
    (void)userdata;

    switch (type) {
    case MD_SPAN_EM:
        return leave_emphasis();
    case MD_SPAN_STRONG:
        return leave_strong();
    case MD_SPAN_A:
        return leave_link();
    case MD_SPAN_IMG:
        return 0;
    case MD_SPAN_CODE:
        return 0;
    default:
        assert(!"unhandled span type");
    }
}

static int text(MD_TEXTTYPE type, const MD_CHAR *text, MD_SIZE size,
                void *userdata)
{
    (void)userdata;

    if (*text_mode == suppress_text)
        return 0;

    switch (type) {
    case MD_TEXT_NORMAL:
        return print_text(text, size);
    case MD_TEXT_NULLCHAR:
        return print_nullchar();
    case MD_TEXT_BR:
        return print_hard_break();
    case MD_TEXT_SOFTBR:
        return print_soft_break();
    case MD_TEXT_ENTITY:
        return print_entity(text, size);
    case MD_TEXT_CODE:
        return print_code(text, size);
    default:
        assert(!"unhandled text type");
    }
}

static const MD_PARSER parser = {
    .flags = MD_FLAG_NOHTML,
    .enter_block = enter_block,
    .leave_block = leave_block,
    .enter_span = enter_span,
    .leave_span = leave_span,
    .text = text
};

static int convert_markdown(const char *text, unsigned int length)
{
    print_document_header();
    return md_parse(text, length, &parser, NULL);
}

//======//
// Main //
//======//

static void read_file(FILE *instream, char **text_out, size_t *size_out)
{
    FILE *memstream = open_memstream(text_out, size_out);

    if (!memstream) {
        error("failed to create memstream: %s", strerror(errno));
        exit(1);
    }

    while (!feof(instream) && !ferror(instream)) {
        char buffer[4096];

        size_t bytes = fread(buffer, 1, sizeof(buffer), instream);

        fwrite(buffer, 1, bytes, memstream);
    }

    fclose(memstream);
}

static void infer_title_and_section(char *path)
{
    char *name = basename(path);
    char *ext = strrchr(name, '.');

    if (!ext || strcmp(ext, ".md") != 0) {
        title = path;
        return;
    }

    *ext = '\0';

    char *sect = strrchr(name, '.');

    if (!sect) {
        title = name;
        return;
    }

    *sect = '\0';
    title = name;
    section = sect + 1;
}

int main(int argc, char **argv)
{
#ifdef _HAS_SIGTRACE
    sigtrace(sigtrace_faults);
#endif

    int inarg = parse_options(argc, argv);
    char *inpath = argv[inarg];

    if (inarg + 1 < argc)
        error("cannot process more than one input file at a time");

    FILE *instream;

    if (inpath) {
        instream = fopen(inpath, "r");

        if (!instream) {
            error("failed to open %s: %s", inpath, strerror(errno));
            exit(1);
        }

        infer_title_and_section(inpath);
    } else {
        instream = stdin;
    }

    char *input;
    size_t size;

    read_file(instream, &input, &size);
    fclose(instream);

    int result = convert_markdown(input, size);

    free(input);

    return result == -1 ? 1 : 0;
}
